# -*- coding: utf-8 -*-
"""ElasticNetReg.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vfsUbeRG-uhAKsLg8nGJP15DIA2nHKpp
"""

pip install scikit-learn pandas numpy plotly

import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from sklearn.model_selection import train_test_split
from sklearn.linear_model import ElasticNet
import pandas as pd
from sklearn.datasets import load_diabetes

data = load_diabetes()
x=pd.DataFrame(data.data,columns=data.feature_names)
y=pd.DataFrame(data.target,columns=["target"])

#Step 2: Splitting it into training set and testing set

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3, random_state=0)

#Step 3: implementing Elastic net regression

elastic_net=ElasticNet(alpha=0.5,l1_ratio=0.5,max_iter=10000,random_state=0)
regressor=elastic_net.fit(x_train,y_train)
#Step 4: Predicting the test set results

y_pred=regressor.predict(x_test)

# Step 5: Visualising
fig = go.Figure()
fig.add_trace(go.Scatter(x=y_test["target"], y=y_pred.flatten(),mode='markers'))
fig.add_trace(go.Scatter(x=[0,350], y=[0,350], mode='lines'))
fig.update_layout(title='Actual vs Predicted', xaxis_title='Actual', yaxis_title='Predicted')
fig.show()