# -*- coding: utf-8 -*-
"""LinearReg.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vfsUbeRG-uhAKsLg8nGJP15DIA2nHKpp
"""

pip install scikit-learn pandas numpy plotly

import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

# Step 1: Creating a complex dataset

np.random.seed(0)
x=np.linspace(0,10,100)
y=3*x**2+2*x+np.random.normal(0,10,100)

#Step 2: Splitting it into training set and testing set

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state=42)

#Step 3: implementing Linear regression

model = LinearRegression()
x_train=x_train.reshape(-1,1)
model.fit(x_train,y_train)
x_test=x_test.reshape(-1,1)
y_pred=model.predict(x_test)

# Step 5: Visualising
fig = go.Figure()
fig.add_trace(go.Scatter(x=x_test.flatten(), y=y_test, mode='markers', name='Actual Data'))
fig.add_trace(go.Scatter(x=x_test.flatten(), y=y_pred, mode='lines', name='Linear Reg line'))
fig.update_layout(title='Linear Regression', xaxis_title='Independent variable', yaxis_title='Dependent Variable')
fig.show()